title: Margaux Gaillard
description: Ingénieure R&D – Vision par ordinateur & Science des matériaux
email: margaux.gaillard@sfr.fr
linkedin_username: margaux-gaillard

sass:
  style: compressed

show_downloads: false
google_analytics:
theme: minima
header_pages:
  - index.md
  - r&d-materiaux.md
  - computer-vision.md
